### ISSUE TITLE
Dark theme problem

### ISSUE THREAD

**Issue by wangxa** [vinceliuice/matcha#13]
```
(gtk3-widget-factory:6540): Gtk-WARNING **: Theme parsing error: gtk.css:3404:12: Expected a length

(gtk3-widget-factory:6540): Gtk-WARNING **: Theme parsing error: gtk.css:3405:13: Expected a length

(gtk3-widget-factory:6540): Gtk-WARNING **: Theme parsing error: gtk.css:3408:12: Expected a length

(gtk3-widget-factory:6540): Gtk-WARNING **: Theme parsing error: gtk.css:3409:15: Junk at end of value for padding
```

The reason is that the `rem()` is not supported. This error is also in `gtk-dark.css`.

**Comment by vinceliuice** [comment]
Thanks! I,ll fix this!

**Comment by vinceliuice** [comment]
Fixed

**Comment by wangxa** [comment]
I saw your solution: simply removing the snippet from `gtk-3.0/sass/_applications.scss`. I have another way to resolve this error:

At the beginning of `gtk-3.0/sass/_applications.scss`, we can add the following codes:
```scss
$em-base: 16px;

@function strip-units($value) {
  @return ($value / ($value * 0 + 1));
}

@function rem($pxval) {
  $pxval: strip-units($pxval);
 
  $base: $em-base;
  $base: strip-units($base);
 
  @return ($pxval / $base) * 1rem;
}
```

Then the `parse-sass.sh` can convert pixel to the corresponding rem value.
